### ISSUE TITLE
ORCID are duplicated in two sections

### ISSUE THREAD

**Issue by JKChang2015** [EBI-Metabolights/guides#14]
Quick start Guide -> Create account

<img width="861" alt="image" src="https://user-images.githubusercontent.com/16242098/92570782-378ada00-f27a-11ea-87bd-8dda6a303ad9.png">

Metabolights Account -> ORCID

<img width="886" alt="image" src="https://user-images.githubusercontent.com/16242098/92570932-63a65b00-f27a-11ea-9944-2ef981927f4f.png">

**Comment by Keeva-ML** [comment]
Thanks. This is on pupose - quick guide section & more detailed section.
